services:
  woovi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: woovi-pedrodecf
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
